In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore') 
from pylab import rcParams
rcParams["figure.figsize"]=30,16

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = pd.read_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v12/v_12.xlsx",sheet_name = 'ln_orig')
data.head()

,OpportunityID_ren,accountnumber,OpportunityID,lnlexidsele,inputcheckbusname,inputcheckbusaltname,inputcheckbusaddr,inputcheckbuscity,inputcheckbusstate,inputcheckbuszip,...,model1rc5,model1rc6,model2name,model2score,model2rc1,model2rc2,model2rc3,model2rc4,model2rc5,model2rc6
0,0062M00000gYsKAQA0,LCFLN202208126655,0062M00000gYsKAQA0,7.278946e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,691.0,B026,B052,B036,B037,NaN,NaN
1,0062M00000gYSqdQAG,LCFLN202208126660,0062M00000gYSqdQAG,0.000000e+00,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,222.0,B068,NaN,NaN,NaN,NaN,NaN
2,0062M00000itNw6QAE,LCFLN202208127456,0062M00000itNw6QAE,7.087273e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,704.0,B069,B063,B052,B066,NaN,NaN
3,0062M00000ito3xQAA,LCFLN202208127457,0062M00000ito3xQAA,4.411074e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,692.0,B026,B069,B066,B076,NaN,NaN
4,0062M00000n0BgNQAU,LCFLN202208130968,0062M00000n0BgNQAU,1.345410e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,708.0,B069,B036,B052,B070,NaN,NaN

In [4]:
'WriteOff_YN' in data.columns

False

In [5]:
wo = pd.read_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v12/v_12.xlsx",sheet_name = 'ren_orig')

In [6]:
wo.columns

Index(['OpportunityID_ren', 'CreatedDate', 'FundedDate', 'OpportunityName',
       'Priordeal_OppID', 'Renewal_PreviousCollectionStatus',
       'Renewal_PreviousPace', 'Renewal_PreviousPaidPercentageOfRTR',
       'Renewal_PreviousCreditScore', 'Renewal_CountPreviousDeals',
       'Renewal_PreviousCountBounces', 'Renewal_PreviousPosition',
       'Renewal_PreviousHBwLCF', 'Renewal_PreviousHBwoLCF',
       'Renewal_PreviousAvgMonthRevenue', 'Renewal_PreviousAvgDailyBalance',
       'Renewal_TwoWeekBounces', 'NumberOfBankStatements',
       'Last3Months_MA_OverdraftDays', 'Last3Months_MA_NumReturnItems',
       'Last3Months_Sum_NumReturnItems', 'LastBankStatement_OverdraftDays',
       'Last3Months_MA_AdjustedMonthlyDeposits',
       'Last3Months_MA_AvgDailyBalance', 'Credit_Score__c',
       'Time_in_Business__c', 'Is_this_Business_home_based__c',
       'BBC_Position__c', 'HB_with_LCF_Payment__c', 'HBwoLCF',
       'Contract_HoldBack__c', 'Last3Statments_MA_AdjustedMonthlyDeposits',
       'Last3Statments_MA_AvgDailyBalance', 'Last3Statments_MA_ReturnItemDays',
       'Last3Statments_MA_OverdraftDays', 'Last3Statments_MA_NumReturnItems',
       'Last3Statments_Sum_NumReturnItems', 'FundedAmount', 'Paybackamount',
       'NewDeal_YN', 'ActiveDeal_YN', 'WriteOff_YN',
       'FundedWriteOffAmount_Gross', 'WOGross_AdvanceBalance', 'NetWO',
       'Industry', 'Industry_Group__c', 'Avg_ReturnItemdays',
       'LatestMonth_ReturnItemDays', 'PctChangeInReveune',
       'PctAvgDailybalance2AvgMonthlyDeposits',
       'TwoMonthAvg_AdjustedMonthlyDeposits', 'AdjustedMonthlyDeposits',
       'drop_percent', 'Drop_category'],
      dtype='object')

In [7]:
wo = wo[['OpportunityID_ren','WriteOff_YN']]

In [8]:
wo

       OpportunityID_ren  WriteOff_YN
0     0062M00000o8ivqQAA          0.0
1     0062M00000hmHKAQA2          1.0
2     0062M00000kxeWLQAY          0.0
3     0062M00000mTGVnQAO          1.0
4     0062M00000gb1LRQAY          0.0
...                  ...          ...
3963  0062M00000lWtjxQAC          0.0
3964  0062M00000bnAyFQAU          1.0
3965  0062M00000dioFlQAI          0.0
3966  0062M00000bngjMQAQ          1.0
3967  0062M00000nXWJ1QAO          0.0

[3968 rows x 2 columns]

In [9]:
d = pd.merge(data, wo, on="OpportunityID_ren")

In [10]:
d

,OpportunityID_ren,accountnumber,OpportunityID,lnlexidsele,inputcheckbusname,inputcheckbusaltname,inputcheckbusaddr,inputcheckbuscity,inputcheckbusstate,inputcheckbuszip,...,model1rc6,model2name,model2score,model2rc1,model2rc2,model2rc3,model2rc4,model2rc5,model2rc6,WriteOff_YN
0,0062M00000gYsKAQA0,LCFLN202208126655,0062M00000gYsKAQA0,7.278946e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,691.0,B026,B052,B036,B037,NaN,NaN,0.0
1,0062M00000gYSqdQAG,LCFLN202208126660,0062M00000gYSqdQAG,0.000000e+00,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,222.0,B068,NaN,NaN,NaN,NaN,NaN,0.0
2,0062M00000itNw6QAE,LCFLN202208127456,0062M00000itNw6QAE,7.087273e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,704.0,B069,B063,B052,B066,NaN,NaN,0.0
3,0062M00000ito3xQAA,LCFLN202208127457,0062M00000ito3xQAA,4.411074e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,692.0,B026,B069,B066,B076,NaN,NaN,0.0
4,0062M00000n0BgNQAU,LCFLN202208130968,0062M00000n0BgNQAU,1.345410e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,708.0,B069,B036,B052,B070,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,0062M00000gYcpIQAS,LCFLN202208126604,0062M00000gYcpIQAS,1.337832e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,652.0,B026,B069,B034,B052,NaN,NaN,0.0
3685,0062M00000gYdrBQAS,LCFLN202208126606,0062M00000gYdrBQAS,1.335285e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,619.0,B026,B074,B063,B070,NaN,NaN,0.0
3686,0062M00000gYfg0QAC,LCFLN202208126608,0062M00000gYfg0QAC,5.107907e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,684.0,B026,B078,B063,B037,NaN,NaN,1.0
3687,0062M00000gYic7QAC,LCFLN202208126614,0062M00000gYic7QAC,2.199165e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,222.0,B068,NaN,NaN,NaN,NaN,NaN,1.0
3688,0062M00000itmCrQAI,LCFLN202208127451,0062M00000itmCrQAI,1.339115e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,622.0,B026,B074,B069,B034,NaN,NaN,0.0

In [11]:
data = d.copy()

# Business Activity Attributes
* businessaddrcount	
* businessrecordtimeoldest	
* businessrecordtimenewest	
* businessrecordupdated12m	
* businessactivity03m	
* businessactivity06m	
* businessactivity12m

In [12]:
business_activity_attributes = ['businessaddrcount',
                                'businessrecordtimeoldest',
                                'businessrecordtimenewest',
                                'businessrecordupdated12m',
                                'businessactivity03m',
                                'businessactivity06m',
                                'businessactivity12m']
print(len(business_activity_attributes))

7

In [13]:
business_activity_attributes.append('OpportunityID_ren')
business_activity_attributes.append('WriteOff_YN')

In [14]:
df = data[business_activity_attributes]

In [15]:
df.shape

(3689, 9)

In [16]:
df.describe()

,businessaddrcount,businessrecordtimeoldest,businessrecordtimenewest,businessrecordupdated12m,businessactivity03m,businessactivity06m,businessactivity12m,WriteOff_YN
count,3689.000000,3689.000000,3689.000000,3689.000000,3689.000000,3689.000000,3689.000000,3689.000000
mean,1.533207,81.004608,2.413662,0.676877,1.691786,1.809433,1.902413,0.265926
std,1.801435,135.537054,13.235322,0.719808,1.546685,1.646418,1.795154,0.441885
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,1.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,33.000000,1.000000,1.000000,2.000000,2.000000,2.000000,0.000000
75%,2.000000,100.000000,1.000000,1.000000,3.000000,3.000000,3.000000,1.000000
max,13.000000,1468.000000,312.000000,1.000000,5.000000,5.000000,5.000000,1.000000

In [17]:
round(df.corr()['WriteOff_YN'].sort_values(),3)

businessrecordtimeoldest   -0.094
businessaddrcount          -0.046
businessrecordtimenewest   -0.020
businessactivity03m        -0.017
businessrecordupdated12m   -0.013
businessactivity06m        -0.007
businessactivity12m         0.002
WriteOff_YN                 1.000
Name: WriteOff_YN, dtype: float64

In [18]:
for i in df.columns:
  print('\033[1m'+'attribute_name :', i+'\033[0m')
  print(df[i].value_counts())

attribute_name : businessaddrcount
 1.0     1506
 2.0      657
-1.0      537
 3.0      400
 4.0      212
 0.0      168
 5.0       84
 6.0       59
 7.0       25
 8.0       19
 9.0       10
 11.0       9
 10.0       1
 12.0       1
 13.0       1
Name: businessaddrcount, dtype: int64
attribute_name : businessrecordtimeoldest
-1.0      549
 9.0       68
 12.0      61
 11.0      61
 15.0      59
         ...
 884.0      1
 663.0      1
 241.0      1
 315.0      1
 321.0      1
Name: businessrecordtimeoldest, Length: 417, dtype: int64
attribute_name : businessrecordtimenewest
 1.0      2739
-1.0       552
 2.0        95
 3.0        49
 4.0        34
          ...
 72.0        1
 38.0        1
 312.0       1
 70.0        1
 89.0        1
Name: businessrecordtimenewest, Length: 66, dtype: int64
attribute_name : businessrecordupdated12m
 1.0    3049
-1.0     552
 0.0      88
Name: businessrecordupdated12m, dtype: int64
attribute_name : businessactivity03m
 2.0    1089
 3.0     753
 1.0     746
-1.0     552
 4.0     275
 0.0     172
 5.0     102
Name: businessactivity03m, dtype: int64
attribute_name : businessactivity06m
 2.0    1024
 3.0     828
-1.0     552
 1.0     505
 4.0     370
 0.0     268
 5.0     142
Name: businessactivity06m, dtype: int64
attribute_name : businessactivity12m
 2.0    839
 3.0    782
-1.0    552
 4.0    502
 0.0    420
 1.0    358
 5.0    236
Name: businessactivity12m, dtype: int64
attribute_name : OpportunityID_ren
0062M00000gYsKAQA0    1
0062M00000jy6UwQAI    1
0062M00000kylbJQAQ    1
0062M00000kylvVQAQ    1
0062M00000lrMH7QAM    1
                     ..
0062M00000np50MQAQ    1
0062M00000mUMUHQA4    1
0062M00000mUnmUQAS    1
0062M00000jKGB5QAO    1
0062M00000itmCrQAI    1
Name: OpportunityID_ren, Length: 3689, dtype: int64
attribute_name : WriteOff_YN
0.0    2708
1.0     981
Name: WriteOff_YN, dtype: int64

In [19]:
df.isna().sum()

businessaddrcount           0
businessrecordtimeoldest    0
businessrecordtimenewest    0
businessrecordupdated12m    0
businessactivity03m         0
businessactivity06m         0
businessactivity12m         0
OpportunityID_ren           0
WriteOff_YN                 0
dtype: int64

In [ ]:
# df.drop(['inquiryconsumeraddressssn'],axis='columns',inplace = True)

In [20]:
df.columns

Index(['businessaddrcount', 'businessrecordtimeoldest',
       'businessrecordtimenewest', 'businessrecordupdated12m',
       'businessactivity03m', 'businessactivity06m', 'businessactivity12m',
       'OpportunityID_ren', 'WriteOff_YN'],
      dtype='object')

In [21]:
round(df.corr()['WriteOff_YN'],3)

businessaddrcount          -0.046
businessrecordtimeoldest   -0.094
businessrecordtimenewest   -0.020
businessrecordupdated12m   -0.013
businessactivity03m        -0.017
businessactivity06m        -0.007
businessactivity12m         0.002
WriteOff_YN                 1.000
Name: WriteOff_YN, dtype: float64

In [22]:
def business_activity_attributes_FE(df):
  for i in ['businessaddrcount','businessrecordtimeoldest','businessrecordtimenewest']:

    if i == 'OpportunityID_ren' or i == 'WriteOff_YN':
       continue
    df[i+'_value'] = df[i].apply(lambda x: 0 if x < 0 else x)
    df[i+'_flag'] = df[i].apply(lambda x: 1 if x < 0 else 0)
    df.drop(i,axis = 'columns',inplace = True)

In [23]:
df = pd.get_dummies(df, columns=['businessrecordupdated12m','businessactivity06m','businessactivity03m','businessactivity12m'])

In [24]:
df

,businessaddrcount,businessrecordtimeoldest,businessrecordtimenewest,OpportunityID_ren,WriteOff_YN,businessrecordupdated12m_-1.0,businessrecordupdated12m_0.0,businessrecordupdated12m_1.0,businessactivity06m_-1.0,businessactivity06m_0.0,...,businessactivity03m_3.0,businessactivity03m_4.0,businessactivity03m_5.0,businessactivity12m_-1.0,businessactivity12m_0.0,businessactivity12m_1.0,businessactivity12m_2.0,businessactivity12m_3.0,businessactivity12m_4.0,businessactivity12m_5.0
0,6.0,51.0,1.0,0062M00000gYsKAQA0,0.0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
1,-1.0,-1.0,-1.0,0062M00000gYSqdQAG,0.0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
2,1.0,136.0,1.0,0062M00000itNw6QAE,0.0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,3.0,306.0,1.0,0062M00000ito3xQAA,0.0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,3.0,32.0,1.0,0062M00000n0BgNQAU,0.0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,1.0,112.0,1.0,0062M00000gYcpIQAS,0.0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3685,1.0,23.0,1.0,0062M00000gYdrBQAS,0.0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3686,6.0,321.0,1.0,0062M00000gYfg0QAC,1.0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
3687,-1.0,-1.0,-1.0,0062M00000gYic7QAC,1.0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
3688,3.0,28.0,1.0,0062M00000itmCrQAI,0.0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0

In [25]:
business_activity_attributes_FE(df)
df

,OpportunityID_ren,WriteOff_YN,businessrecordupdated12m_-1.0,businessrecordupdated12m_0.0,businessrecordupdated12m_1.0,businessactivity06m_-1.0,businessactivity06m_0.0,businessactivity06m_1.0,businessactivity06m_2.0,businessactivity06m_3.0,...,businessactivity12m_2.0,businessactivity12m_3.0,businessactivity12m_4.0,businessactivity12m_5.0,businessaddrcount_value,businessaddrcount_flag,businessrecordtimeoldest_value,businessrecordtimeoldest_flag,businessrecordtimenewest_value,businessrecordtimenewest_flag
0,0062M00000gYsKAQA0,0.0,0,0,1,0,0,0,0,0,...,0,0,1,0,6.0,0,51.0,0,1.0,0
1,0062M00000gYSqdQAG,0.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0.0,1,0.0,1,0.0,1
2,0062M00000itNw6QAE,0.0,0,0,1,0,0,1,0,0,...,1,0,0,0,1.0,0,136.0,0,1.0,0
3,0062M00000ito3xQAA,0.0,0,0,1,0,0,0,1,0,...,1,0,0,0,3.0,0,306.0,0,1.0,0
4,0062M00000n0BgNQAU,0.0,0,0,1,0,0,0,0,0,...,0,0,1,0,3.0,0,32.0,0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,0062M00000gYcpIQAS,0.0,0,0,1,0,0,1,0,0,...,0,0,0,0,1.0,0,112.0,0,1.0,0
3685,0062M00000gYdrBQAS,0.0,0,0,1,0,0,0,1,0,...,0,1,0,0,1.0,0,23.0,0,1.0,0
3686,0062M00000gYfg0QAC,1.0,0,0,1,0,1,0,0,0,...,0,0,0,0,6.0,0,321.0,0,1.0,0
3687,0062M00000gYic7QAC,1.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0.0,1,0.0,1,0.0,1
3688,0062M00000itmCrQAI,0.0,0,0,1,0,0,0,0,0,...,0,0,1,0,3.0,0,28.0,0,1.0,0

In [26]:
round(df.corr()['WriteOff_YN'].sort_values(),3)

businessrecordtimeoldest_value   -0.094
businessaddrcount_value          -0.047
businessactivity12m_0.0          -0.036
businessactivity03m_5.0          -0.034
businessactivity06m_5.0          -0.028
businessactivity06m_0.0          -0.024
businessactivity03m_1.0          -0.022
businessactivity06m_1.0          -0.020
businessrecordtimenewest_value   -0.020
businessactivity12m_5.0          -0.017
businessactivity03m_4.0          -0.014
businessactivity03m_0.0          -0.014
businessrecordupdated12m_0.0     -0.014
businessrecordupdated12m_1.0     -0.009
businessactivity12m_3.0          -0.007
businessactivity06m_3.0           0.001
businessactivity06m_4.0           0.001
businessactivity03m_3.0           0.003
businessactivity12m_2.0           0.006
businessactivity12m_1.0           0.010
businessrecordtimeoldest_flag     0.016
businessrecordtimenewest_flag     0.016
businessactivity03m_-1.0          0.016
businessactivity06m_-1.0          0.016
businessrecordupdated12m_-1.0     0.016
businessactivity12m_-1.0          0.016
businessaddrcount_flag            0.019
businessactivity12m_4.0           0.022
businessactivity06m_2.0           0.027
businessactivity03m_2.0           0.031
WriteOff_YN                       1.000
Name: WriteOff_YN, dtype: float64

In [27]:
data[business_activity_attributes].corr()['WriteOff_YN'].sort_values()

businessrecordtimeoldest   -0.093781
businessaddrcount          -0.046351
businessrecordtimenewest   -0.020205
businessactivity03m        -0.016521
businessrecordupdated12m   -0.012801
businessactivity06m        -0.007474
businessactivity12m         0.001618
WriteOff_YN                 1.000000
Name: WriteOff_YN, dtype: float64

In [28]:
df.to_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v12/FE_V12_CSVs/business_activity_attributes.xlsx", index = False)