In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore') 
from pylab import rcParams
rcParams["figure.figsize"]=30,16

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = pd.read_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v11/v11_3.xlsx",sheet_name = 'ren_ln_orig')
data.head()

,OpportunityID_ren,accountnumber,OpportunityID,lnlexidsele,inputcheckbusname,inputcheckbusaltname,inputcheckbusaddr,inputcheckbuscity,inputcheckbusstate,inputcheckbuszip,...,model1rc5,model1rc6,model2name,model2score,model2rc1,model2rc2,model2rc3,model2rc4,model2rc5,model2rc6
0,0062M00000gYqZQQA0,LCFLN202208126653,0062M00000gYqZQQA0,1.069630e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,560.0,B078,B026,B063,B074,NaN,NaN
1,0062M00000gYSpGQAW,LCFLN202208126658,0062M00000gYSpGQAW,5.004454e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,723.0,B069,B063,B031,B066,NaN,NaN
2,0062M00000gYsQcQAK,LCFLN202208126659,0062M00000gYsQcQAK,9.550183e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,702.0,B034,B052,B036,B037,NaN,NaN
3,0062M00000n0BEfQAM,LCFLN202208130965,0062M00000n0BEfQAM,1.619373e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,562.0,B078,B026,B074,B063,NaN,NaN
4,0062M00000gYTaCQAW,LCFLN202208126663,0062M00000gYTaCQAW,2.354679e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,573.0,B063,B026,B078,B074,NaN,NaN

In [4]:
'WriteOff_YN' in data.columns

False

In [5]:
wo = pd.read_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v11/v11_3.xlsx",sheet_name = 'Ren_orig')

In [6]:
wo.columns

Index(['OpportunityID', 'CreatedDate', 'FundedDate', 'OpportunityName',
       'Priordeal_OppID', 'Renewal_PreviousCollectionStatus',
       'Renewal_PreviousPace', 'Renewal_PreviousPaidPercentageOfRTR',
       'Renewal_PreviousCreditScore', 'Renewal_CountPreviousDeals',
       'Renewal_PreviousCountBounces', 'Renewal_PreviousPosition',
       'Renewal_PreviousHBwLCF', 'Renewal_PreviousHBwoLCF',
       'Renewal_PreviousAvgMonthRevenue', 'Renewal_PreviousAvgDailyBalance',
       'Renewal_TwoWeekBounces', 'NumberOfBankStatements',
       'Last3Months_MA_OverdraftDays', 'Last3Months_MA_NumReturnItems',
       'Last3Months_Sum_NumReturnItems', 'LastBankStatement_OverdraftDays',
       'Last3Months_MA_AdjustedMonthlyDeposits',
       'Last3Months_MA_AvgDailyBalance', 'Credit_Score__c',
       'Time_in_Business__c', 'Is_this_Business_home_based__c',
       'BBC_Position__c', 'HB_with_LCF_Payment__c', 'HBwoLCF',
       'Contract_HoldBack__c', 'Last3Statments_MA_AdjustedMonthlyDeposits',
       'Last3Statments_MA_AvgDailyBalance', 'Last3Statments_MA_ReturnItemDays',
       'Last3Statments_MA_OverdraftDays', 'Last3Statments_MA_NumReturnItems',
       'Last3Statments_Sum_NumReturnItems', 'FundedAmount', 'Paybackamount',
       'NewDeal_YN', 'ActiveDeal_YN', 'WriteOff_YN',
       'FundedWriteOffAmount_Gross', 'WOGross_AdvanceBalance', 'NetWO',
       'Industry', 'Industry_Group__c', 'Avg_ReturnItemdays',
       'LatestMonth_ReturnItemDays', 'PctChangeInReveune',
       'PctAvgDailybalance2AvgMonthlyDeposits',
       'TwoMonthAvg_AdjustedMonthlyDeposits', 'AdjustedMonthlyDeposits',
       'drop_percent', 'Drop_category'],
      dtype='object')

In [7]:
wo = wo[['OpportunityID','WriteOff_YN']]

In [8]:
wo

           OpportunityID  WriteOff_YN
0     0062M00000mTGVnQAO          1.0
1     0062M00000o96yhQAA          0.0
2     0062M00000mfz6iQAA          0.0
3     0062M00000lVi6gQAC          0.0
4     0062M00000mg31dQAA          0.0
...                  ...          ...
3534  0062M00000oY7fdQAC          1.0
3535  0062M00000bmKPLQA2          1.0
3536  0062M00000bmhkAQAQ          1.0
3537  0062M00000lWtjxQAC          0.0
3538  0062M00000bnAyFQAU          1.0

[3539 rows x 2 columns]

In [9]:
d = pd.merge(data, wo, on="OpportunityID")

In [10]:
d

,OpportunityID_ren,accountnumber,OpportunityID,lnlexidsele,inputcheckbusname,inputcheckbusaltname,inputcheckbusaddr,inputcheckbuscity,inputcheckbusstate,inputcheckbuszip,...,model1rc6,model2name,model2score,model2rc1,model2rc2,model2rc3,model2rc4,model2rc5,model2rc6,WriteOff_YN
0,0062M00000gYqZQQA0,LCFLN202208126653,0062M00000gYqZQQA0,1.069630e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,560.0,B078,B026,B063,B074,NaN,NaN,0.0
1,0062M00000gYSpGQAW,LCFLN202208126658,0062M00000gYSpGQAW,5.004454e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,723.0,B069,B063,B031,B066,NaN,NaN,0.0
2,0062M00000gYsQcQAK,LCFLN202208126659,0062M00000gYsQcQAK,9.550183e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,702.0,B034,B052,B036,B037,NaN,NaN,0.0
3,0062M00000n0BEfQAM,LCFLN202208130965,0062M00000n0BEfQAM,1.619373e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,562.0,B078,B026,B074,B063,NaN,NaN,0.0
4,0062M00000gYTaCQAW,LCFLN202208126663,0062M00000gYTaCQAW,2.354679e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,573.0,B063,B026,B078,B074,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3377,0062M00000lTxv8QAC,LCFLN202208129165,0062M00000lTxv8QAC,1.197487e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,659.0,B026,B069,B066,B070,NaN,NaN,0.0
3378,0062M00000lTxyLQAS,LCFLN202208129166,0062M00000lTxyLQAS,1.342359e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,688.0,B034,B069,B037,B036,NaN,NaN,0.0
3379,0062M00000jzsJkQAI,LCFLN202208128064,0062M00000jzsJkQAI,6.488768e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,711.0,B017,B066,B052,B036,NaN,NaN,1.0
3380,0062M00000l01oMQAQ,LCFLN202208128630,0062M00000l01oMQAQ,1.368324e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,222.0,B068,NaN,NaN,NaN,NaN,NaN,1.0
3381,0062M00000l02kTQAQ,LCFLN202208128631,0062M00000l02kTQAQ,2.554980e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,581.0,B075,B063,B026,B074,NaN,NaN,0.0

In [11]:
data = d.copy()

# Business to Person Link Attributes
* BusAddrPersonNameOverlap
* BusTINPersonAddrOverlap
* BusTINPersonPhoneOverlap
* BusTINPersonOverlap

In [12]:
b_to_p_link = ['busaddrpersonnameoverlap',
'busTINpersonaddroverlap',
'busTINpersonphoneoverlap',
'busTINpersonoverlap']

In [13]:
# b_to_p_link = list(map(str.lower, b_to_p_link)) 
# b_to_p_link

In [14]:
b_to_p_link.append('OpportunityID')
b_to_p_link.append('WriteOff_YN')

In [15]:
df = data[b_to_p_link]

In [16]:
df.shape

(3382, 6)

In [17]:
df.describe()

,busaddrpersonnameoverlap,busTINpersonaddroverlap,busTINpersonphoneoverlap,busTINpersonoverlap,WriteOff_YN
count,3382.000000,3382.0,3382.0,3382.0,3382.000000
mean,1.122413,-1.0,-1.0,-1.0,0.264341
std,0.639182,0.0,0.0,0.0,0.441047
min,0.000000,-1.0,-1.0,-1.0,0.000000
25%,1.000000,-1.0,-1.0,-1.0,0.000000
50%,1.000000,-1.0,-1.0,-1.0,0.000000
75%,2.000000,-1.0,-1.0,-1.0,1.000000
max,2.000000,-1.0,-1.0,-1.0,1.000000

In [18]:
round(df.corr()['WriteOff_YN'].sort_values(),3)

busaddrpersonnameoverlap   -0.002
WriteOff_YN                 1.000
busTINpersonaddroverlap       NaN
busTINpersonphoneoverlap      NaN
busTINpersonoverlap           NaN
Name: WriteOff_YN, dtype: float64

In [19]:
for i in df.columns:
  print('\033[1m'+'attribute_name :', i+'\033[0m')
  print(df[i].value_counts())

attribute_name : busaddrpersonnameoverlap
1.0    1950
2.0     923
0.0     509
Name: busaddrpersonnameoverlap, dtype: int64
attribute_name : busTINpersonaddroverlap
-1.0    3382
Name: busTINpersonaddroverlap, dtype: int64
attribute_name : busTINpersonphoneoverlap
-1.0    3382
Name: busTINpersonphoneoverlap, dtype: int64
attribute_name : busTINpersonoverlap
-1.0    3382
Name: busTINpersonoverlap, dtype: int64
attribute_name : OpportunityID
0062M00000gYqZQQA0    1
0062M00000lrP8bQAE    1
0062M00000g8ojxQAA    1
0062M00000g8pG8QAI    1
0062M00000lrf8LQAQ    1
                     ..
0062M00000oPWWiQAO    1
0062M00000noKxKQAU    1
0062M00000noLSAQA2    1
0062M00000nomOVQAY    1
0062M00000l02kTQAQ    1
Name: OpportunityID, Length: 3382, dtype: int64
attribute_name : WriteOff_YN
0.0    2488
1.0     894
Name: WriteOff_YN, dtype: int64

In [20]:
df.isna().sum()

busaddrpersonnameoverlap    0
busTINpersonaddroverlap     0
busTINpersonphoneoverlap    0
busTINpersonoverlap         0
OpportunityID               0
WriteOff_YN                 0
dtype: int64

In [21]:
df.columns

Index(['busaddrpersonnameoverlap', 'busTINpersonaddroverlap',
       'busTINpersonphoneoverlap', 'busTINpersonoverlap', 'OpportunityID',
       'WriteOff_YN'],
      dtype='object')

In [22]:
df.drop(['busTINpersonaddroverlap','busTINpersonphoneoverlap','busTINpersonoverlap'],axis = 1,inplace = True)

In [23]:
df

      busaddrpersonnameoverlap       OpportunityID  WriteOff_YN
0                          1.0  0062M00000gYqZQQA0          0.0
1                          0.0  0062M00000gYSpGQAW          0.0
2                          1.0  0062M00000gYsQcQAK          0.0
3                          1.0  0062M00000n0BEfQAM          0.0
4                          1.0  0062M00000gYTaCQAW          1.0
...                        ...                 ...          ...
3377                       1.0  0062M00000lTxv8QAC          0.0
3378                       2.0  0062M00000lTxyLQAS          0.0
3379                       1.0  0062M00000jzsJkQAI          1.0
3380                       1.0  0062M00000l01oMQAQ          1.0
3381                       0.0  0062M00000l02kTQAQ          0.0

[3382 rows x 3 columns]

In [24]:
df = pd.get_dummies(df,columns = ['busaddrpersonnameoverlap'])
df

,OpportunityID,WriteOff_YN,busaddrpersonnameoverlap_0.0,busaddrpersonnameoverlap_1.0,busaddrpersonnameoverlap_2.0
0,0062M00000gYqZQQA0,0.0,0,1,0
1,0062M00000gYSpGQAW,0.0,1,0,0
2,0062M00000gYsQcQAK,0.0,0,1,0
3,0062M00000n0BEfQAM,0.0,0,1,0
4,0062M00000gYTaCQAW,1.0,0,1,0
...,...,...,...,...,...
3377,0062M00000lTxv8QAC,0.0,0,1,0
3378,0062M00000lTxyLQAS,0.0,0,0,1
3379,0062M00000jzsJkQAI,1.0,0,1,0
3380,0062M00000l01oMQAQ,1.0,0,1,0
3381,0062M00000l02kTQAQ,0.0,1,0,0

In [25]:
round(df.corr()['WriteOff_YN'].sort_values(),3)

busaddrpersonnameoverlap_0.0   -0.024
busaddrpersonnameoverlap_2.0   -0.021
busaddrpersonnameoverlap_1.0    0.036
WriteOff_YN                     1.000
Name: WriteOff_YN, dtype: float64

In [26]:
round(data[b_to_p_link].corr()['WriteOff_YN'].sort_values(),3)

busaddrpersonnameoverlap   -0.002
WriteOff_YN                 1.000
busTINpersonaddroverlap       NaN
busTINpersonphoneoverlap      NaN
busTINpersonoverlap           NaN
Name: WriteOff_YN, dtype: float64

In [27]:
df.to_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v11/b_to_p_link.xlsx")