In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore') 
from pylab import rcParams
rcParams["figure.figsize"]=30,16

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v11/v11_3.xlsx",sheet_name = 'ren_ln_orig')
data.head()

,OpportunityID_ren,accountnumber,OpportunityID,lnlexidsele,inputcheckbusname,inputcheckbusaltname,inputcheckbusaddr,inputcheckbuscity,inputcheckbusstate,inputcheckbuszip,...,model1rc5,model1rc6,model2name,model2score,model2rc1,model2rc2,model2rc3,model2rc4,model2rc5,model2rc6
0,0062M00000gYqZQQA0,LCFLN202208126653,0062M00000gYqZQQA0,1.069630e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,560.0,B078,B026,B063,B074,NaN,NaN
1,0062M00000gYSpGQAW,LCFLN202208126658,0062M00000gYSpGQAW,5.004454e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,723.0,B069,B063,B031,B066,NaN,NaN
2,0062M00000gYsQcQAK,LCFLN202208126659,0062M00000gYsQcQAK,9.550183e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,702.0,B034,B052,B036,B037,NaN,NaN
3,0062M00000n0BEfQAM,LCFLN202208130965,0062M00000n0BEfQAM,1.619373e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,562.0,B078,B026,B074,B063,NaN,NaN
4,0062M00000gYTaCQAW,LCFLN202208126663,0062M00000gYTaCQAW,2.354679e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,NaN,SLBO1702_0_2,573.0,B063,B026,B078,B074,NaN,NaN

In [ ]:
'WriteOff_YN' in data.columns

False

In [ ]:
wo = pd.read_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v11/v11_3.xlsx",sheet_name = 'Ren_orig')

In [ ]:
wo.columns

Index(['OpportunityID', 'CreatedDate', 'FundedDate', 'OpportunityName',
       'Priordeal_OppID', 'Renewal_PreviousCollectionStatus',
       'Renewal_PreviousPace', 'Renewal_PreviousPaidPercentageOfRTR',
       'Renewal_PreviousCreditScore', 'Renewal_CountPreviousDeals',
       'Renewal_PreviousCountBounces', 'Renewal_PreviousPosition',
       'Renewal_PreviousHBwLCF', 'Renewal_PreviousHBwoLCF',
       'Renewal_PreviousAvgMonthRevenue', 'Renewal_PreviousAvgDailyBalance',
       'Renewal_TwoWeekBounces', 'NumberOfBankStatements',
       'Last3Months_MA_OverdraftDays', 'Last3Months_MA_NumReturnItems',
       'Last3Months_Sum_NumReturnItems', 'LastBankStatement_OverdraftDays',
       'Last3Months_MA_AdjustedMonthlyDeposits',
       'Last3Months_MA_AvgDailyBalance', 'Credit_Score__c',
       'Time_in_Business__c', 'Is_this_Business_home_based__c',
       'BBC_Position__c', 'HB_with_LCF_Payment__c', 'HBwoLCF',
       'Contract_HoldBack__c', 'Last3Statments_MA_AdjustedMonthlyDeposits',
       'Last3Statments_MA_AvgDailyBalance', 'Last3Statments_MA_ReturnItemDays',
       'Last3Statments_MA_OverdraftDays', 'Last3Statments_MA_NumReturnItems',
       'Last3Statments_Sum_NumReturnItems', 'FundedAmount', 'Paybackamount',
       'NewDeal_YN', 'ActiveDeal_YN', 'WriteOff_YN',
       'FundedWriteOffAmount_Gross', 'WOGross_AdvanceBalance', 'NetWO',
       'Industry', 'Industry_Group__c', 'Avg_ReturnItemdays',
       'LatestMonth_ReturnItemDays', 'PctChangeInReveune',
       'PctAvgDailybalance2AvgMonthlyDeposits',
       'TwoMonthAvg_AdjustedMonthlyDeposits', 'AdjustedMonthlyDeposits',
       'drop_percent', 'Drop_category'],
      dtype='object')

In [ ]:
wo = wo[['OpportunityID','WriteOff_YN']]

In [ ]:
wo

           OpportunityID  WriteOff_YN
0     0062M00000mTGVnQAO          1.0
1     0062M00000o96yhQAA          0.0
2     0062M00000mfz6iQAA          0.0
3     0062M00000lVi6gQAC          0.0
4     0062M00000mg31dQAA          0.0
...                  ...          ...
3534  0062M00000oY7fdQAC          1.0
3535  0062M00000bmKPLQA2          1.0
3536  0062M00000bmhkAQAQ          1.0
3537  0062M00000lWtjxQAC          0.0
3538  0062M00000bnAyFQAU          1.0

[3539 rows x 2 columns]

In [ ]:
d = pd.merge(data, wo, on="OpportunityID")

In [ ]:
d

,OpportunityID_ren,accountnumber,OpportunityID,lnlexidsele,inputcheckbusname,inputcheckbusaltname,inputcheckbusaddr,inputcheckbuscity,inputcheckbusstate,inputcheckbuszip,...,model1rc6,model2name,model2score,model2rc1,model2rc2,model2rc3,model2rc4,model2rc5,model2rc6,WriteOff_YN
0,0062M00000gYqZQQA0,LCFLN202208126653,0062M00000gYqZQQA0,1.069630e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,560.0,B078,B026,B063,B074,NaN,NaN,0.0
1,0062M00000gYSpGQAW,LCFLN202208126658,0062M00000gYSpGQAW,5.004454e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,723.0,B069,B063,B031,B066,NaN,NaN,0.0
2,0062M00000gYsQcQAK,LCFLN202208126659,0062M00000gYsQcQAK,9.550183e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,702.0,B034,B052,B036,B037,NaN,NaN,0.0
3,0062M00000n0BEfQAM,LCFLN202208130965,0062M00000n0BEfQAM,1.619373e+08,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,562.0,B078,B026,B074,B063,NaN,NaN,0.0
4,0062M00000gYTaCQAW,LCFLN202208126663,0062M00000gYTaCQAW,2.354679e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,573.0,B063,B026,B078,B074,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3377,0062M00000lTxv8QAC,LCFLN202208129165,0062M00000lTxv8QAC,1.197487e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,659.0,B026,B069,B066,B070,NaN,NaN,0.0
3378,0062M00000lTxyLQAS,LCFLN202208129166,0062M00000lTxyLQAS,1.342359e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,688.0,B034,B069,B037,B036,NaN,NaN,0.0
3379,0062M00000jzsJkQAI,LCFLN202208128064,0062M00000jzsJkQAI,6.488768e+10,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,711.0,B017,B066,B052,B036,NaN,NaN,1.0
3380,0062M00000l01oMQAQ,LCFLN202208128630,0062M00000l01oMQAQ,1.368324e+11,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,222.0,B068,NaN,NaN,NaN,NaN,NaN,1.0
3381,0062M00000l02kTQAQ,LCFLN202208128631,0062M00000l02kTQAQ,2.554980e+07,1.0,0.0,1.0,1.0,1.0,1.0,...,NaN,SLBO1702_0_2,581.0,B075,B063,B026,B074,NaN,NaN,0.0

In [ ]:
data = d.copy()

# Associate Attributes
* AssociateCount
* AssociateBusinessCount
* AssociateFelonyCount
* AssociateCountWithFelony
* AssociateBankruptCount
* AssociateCountWithBankruptcy
* AssociateBankrupt12MCount
* AssociateLienCount
* AssociateCountWithLien
* AssociateJudgmentCount
* AssociateCountWithJudgment
* AssociateWatchlistCount
* AssociateCityCount
* AssociateCountyCount
* AssociateHighRiskAddrCount
* AssociateHighCrimeAddrCount
* AssociateCurrCount
* AssociateCurrCountWithFelony
* AssociateCurrCountWithBkrpt
* AssociateCurrCountWithLien
* AssociateCurrCountWithJudgment
* AssociateCurrCountWithProp
* AssociateCurrBusinessesTotal
* AssociateCurrSOSCount

In [ ]:
associate_attributes = ['AssociateCount',
'AssociateBusinessCount',
'AssociateFelonyCount',
'AssociateCountWithFelony',
'AssociateBankruptCount',
'AssociateCountWithBankruptcy',
'AssociateBankrupt12MCount',
'AssociateLienCount',
'AssociateCountWithLien',
'AssociateJudgmentCount',
'AssociateCountWithJudgment',
'AssociateWatchlistCount',
'AssociateCityCount',
'AssociateCountyCount',
'AssociateHighRiskAddrCount',
'AssociateHighCrimeAddrCount',
'AssociateCurrCount',
'AssociateCurrCountWithFelony',
'AssociateCurrCountWithBkrpt',
'AssociateCurrCountWithLien',
'AssociateCurrCountWithJudgment',
'AssociateCurrCountWithProp',
'AssociateCurrBusinessesTotal',
'AssociateCurrSOSCount']

In [ ]:
associate_attributes = list(map(str.lower, associate_attributes)) 
associate_attributes

['associatecount',
 'associatebusinesscount',
 'associatefelonycount',
 'associatecountwithfelony',
 'associatebankruptcount',
 'associatecountwithbankruptcy',
 'associatebankrupt12mcount',
 'associateliencount',
 'associatecountwithlien',
 'associatejudgmentcount',
 'associatecountwithjudgment',
 'associatewatchlistcount',
 'associatecitycount',
 'associatecountycount',
 'associatehighriskaddrcount',
 'associatehighcrimeaddrcount',
 'associatecurrcount',
 'associatecurrcountwithfelony',
 'associatecurrcountwithbkrpt',
 'associatecurrcountwithlien',
 'associatecurrcountwithjudgment',
 'associatecurrcountwithprop',
 'associatecurrbusinessestotal',
 'associatecurrsoscount']

In [ ]:
associate_attributes.append('OpportunityID')
associate_attributes.append('WriteOff_YN')

In [ ]:
df = data[associate_attributes]

In [ ]:
df.shape

(3382, 26)

In [ ]:
df.describe()

,associatecount,associatebusinesscount,associatefelonycount,associatecountwithfelony,associatebankruptcount,associatecountwithbankruptcy,associatebankrupt12mcount,associateliencount,associatecountwithlien,associatejudgmentcount,...,associatehighcrimeaddrcount,associatecurrcount,associatecurrcountwithfelony,associatecurrcountwithbkrpt,associatecurrcountwithlien,associatecurrcountwithjudgment,associatecurrcountwithprop,associatecurrbusinessestotal,associatecurrsoscount,WriteOff_YN
count,3382.000000,3382.000000,3382.00000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,...,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000,3382.000000
mean,0.910704,4.263454,0.01094,-0.112064,-0.065937,-0.067120,-0.144885,0.436724,0.070668,0.418391,...,0.081609,0.711709,-0.118569,-0.084270,0.026907,0.082200,0.403016,3.263749,0.465405,0.264341
std,1.442482,22.345743,1.19728,0.420746,0.500309,0.496591,0.367653,2.080028,0.651281,1.451674,...,0.745186,1.293846,0.411119,0.470038,0.603782,0.652424,1.041818,18.362326,1.076689,0.441047
min,-1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,4.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,1.000000,1.000000
max,12.000000,808.000000,21.00000,2.000000,3.000000,3.000000,2.000000,32.000000,3.000000,19.000000,...,6.000000,12.000000,2.000000,3.000000,3.000000,3.000000,8.000000,808.000000,7.000000,1.000000

In [ ]:
df.isna().sum()

associatecount                    0
associatebusinesscount            0
associatefelonycount              0
associatecountwithfelony          0
associatebankruptcount            0
associatecountwithbankruptcy      0
associatebankrupt12mcount         0
associateliencount                0
associatecountwithlien            0
associatejudgmentcount            0
associatecountwithjudgment        0
associatewatchlistcount           0
associatecitycount                0
associatecountycount              0
associatehighriskaddrcount        0
associatehighcrimeaddrcount       0
associatecurrcount                0
associatecurrcountwithfelony      0
associatecurrcountwithbkrpt       0
associatecurrcountwithlien        0
associatecurrcountwithjudgment    0
associatecurrcountwithprop        0
associatecurrbusinessestotal      0
associatecurrsoscount             0
OpportunityID                     0
WriteOff_YN                       0
dtype: int64

In [ ]:
round(df.corr()['WriteOff_YN'].sort_values(),3)

associatecurrcountwithprop       -0.063
associatecountycount             -0.055
associatecitycount               -0.054
associatecount                   -0.049
associateliencount               -0.048
associatecountwithlien           -0.047
associatehighcrimeaddrcount      -0.042
associatebusinesscount           -0.040
associatecurrcountwithlien       -0.036
associatecurrcount               -0.031
associatecountwithjudgment       -0.029
associatecurrbusinessestotal     -0.026
associatejudgmentcount           -0.023
associatecurrsoscount            -0.021
associatecountwithfelony         -0.019
associatewatchlistcount          -0.018
associatehighriskaddrcount       -0.017
associatecurrcountwithjudgment   -0.017
associatefelonycount             -0.016
associatecurrcountwithfelony     -0.015
associatebankrupt12mcount        -0.014
associatecurrcountwithbkrpt      -0.008
associatecountwithbankruptcy     -0.007
associatebankruptcount           -0.004
WriteOff_YN                       1.000
Name: WriteOff_YN, dtype: float64

In [ ]:
for i in df.columns:
  print('\033[1m'+'attribute_name :', i+'\033[0m')
  print(df[i].value_counts())

attribute_name : associatecount
 1.0     1226
 0.0      803
 2.0      510
-1.0      508
 3.0      168
 4.0       86
 5.0       36
 6.0       21
 7.0       14
 8.0        7
 12.0       2
 10.0       1
Name: associatecount, dtype: int64
attribute_name : associatebusinesscount
 0.0      1065
-1.0       508
 1.0       399
 2.0       346
 3.0       214
 4.0       150
 5.0       127
 6.0       120
 7.0        68
 8.0        59
 10.0       33
 9.0        29
 13.0       27
 15.0       26
 12.0       25
 11.0       23
 18.0       21
 14.0       20
 16.0       15
 21.0       11
 17.0       10
 30.0        7
 19.0        6
 28.0        5
 325.0       5
 31.0        5
 22.0        5
 55.0        4
 20.0        4
 29.0        3
 32.0        3
 170.0       3
 23.0        3
 26.0        2
 42.0        2
 71.0        2
 51.0        2
 54.0        2
 90.0        2
 24.0        1
 35.0        1
 808.0       1
 168.0       1
 173.0       1
 25.0        1
 45.0        1
 80.0        1
 75.0        1
 107.0       1
 235.0       1
 96.0        1
 190.0       1
 92.0        1
 129.0       1
 128.0       1
 108.0       1
 104.0       1
 34.0        1
 99.0        1
 268.0       1
Name: associatebusinesscount, dtype: int64
attribute_name : associatefelonycount
 0.0     2747
-1.0      508
 2.0       30
 1.0       29
 5.0       18
 6.0       12
 4.0       10
 3.0        9
 10.0       4
 9.0        4
 19.0       3
 11.0       2
 8.0        2
 16.0       1
 12.0       1
 21.0       1
 7.0        1
Name: associatefelonycount, dtype: int64
attribute_name : associatecountwithfelony
 0.0    2747
-1.0     508
 1.0     125
 2.0       2
Name: associatecountwithfelony, dtype: int64
attribute_name : associatebankruptcount
 0.0    2621
-1.0     508
 1.0     223
 2.0      28
 3.0       2
Name: associatebankruptcount, dtype: int64
attribute_name : associatecountwithbankruptcy
 0.0    2621
-1.0     508
 1.0     227
 2.0      24
 3.0       2
Name: associatecountwithbankruptcy, dtype: int64
attribute_name : associatebankrupt12mcount
 0.0    2857
-1.0     508
 1.0      16
 2.0       1
Name: associatebankrupt12mcount, dtype: int64
attribute_name : associateliencount
 0.0     2217
-1.0      508
 1.0      269
 2.0      139
 3.0       98
 4.0       40
 5.0       34
 6.0       18
 7.0       15
 8.0       10
 9.0        8
 11.0       6
 25.0       4
 10.0       3
 17.0       2
 12.0       2
 21.0       2
 24.0       2
 27.0       1
 15.0       1
 32.0       1
 18.0       1
 13.0       1
Name: associateliencount, dtype: int64
attribute_name : associatecountwithlien
 0.0    2217
 1.0     575
-1.0     508
 2.0      74
 3.0       8
Name: associatecountwithlien, dtype: int64
attribute_name : associatejudgmentcount
 0.0     2029
-1.0      508
 1.0      372
 2.0      209
 3.0      128
 4.0       58
 5.0       38
 7.0       18
 6.0       10
 12.0       4
 10.0       3
 11.0       2
 19.0       1
 9.0        1
 13.0       1
Name: associatejudgmentcount, dtype: int64
attribute_name : associatecountwithjudgment
 0.0    2029
 1.0     758
-1.0     508
 2.0      77
 3.0       6
 4.0       4
Name: associatecountwithjudgment, dtype: int64
attribute_name : associatewatchlistcount
 0.0    2874
-1.0     508
Name: associatewatchlistcount, dtype: int64
attribute_name : associatecitycount
 0.0     1402
 1.0     1000
-1.0      508
 2.0      346
 4.0       61
 3.0       59
 5.0        2
 8.0        2
 6.0        1
 10.0       1
Name: associatecitycount, dtype: int64
attribute_name : associatecountycount
 0.0     1177
 1.0     1072
-1.0      508
 2.0      416
 3.0      125
 4.0       57
 5.0       16
 6.0        7
 12.0       2
 7.0        1
 10.0       1
Name: associatecountycount, dtype: int64
attribute_name : associatehighriskaddrcount
 0.0    2780
-1.0     508
 1.0      90
 2.0       4
Name: associatehighriskaddrcount, dtype: int64
attribute_name : associatehighcrimeaddrcount
 0.0    2305
-1.0     508
 1.0     418
 2.0     104
 3.0      36
 4.0       7
 5.0       2
 6.0       2
Name: associatehighcrimeaddrcount, dtype: int64
attribute_name : associatecurrcount
 1.0     1152
 0.0     1071
-1.0      508
 2.0      397
 3.0      140
 4.0       62
 5.0       37
 8.0        5
 6.0        4
 7.0        4
 12.0       2
Name: associatecurrcount, dtype: int64
attribute_name : associatecurrcountwithfelony
 0.0    2769
-1.0     508
 1.0     103
 2.0       2
Name: associatecurrcountwithfelony, dtype: int64
attribute_name : associatecurrcountwithbkrpt
 0.0    2670
-1.0     508
 1.0     186
 2.0      17
 3.0       1
Name: associatecurrcountwithbkrpt, dtype: int64
attribute_name : associatecurrcountwithlien
 0.0    2335
-1.0     508
 1.0     483
 2.0      52
 3.0       4
Name: associatecurrcountwithlien, dtype: int64
attribute_name : associatecurrcountwithjudgment
 0.0    2165
 1.0     639
-1.0     508
 2.0      63
 3.0       7
Name: associatecurrcountwithjudgment, dtype: int64
attribute_name : associatecurrcountwithprop
 0.0    1603
 1.0     877
-1.0     508
 2.0     266
 3.0      68
 4.0      52
 5.0       4
 8.0       2
 7.0       2
Name: associatecurrcountwithprop, dtype: int64
attribute_name : associatecurrbusinessestotal
 0.0      1289
-1.0       508
 1.0       394
 2.0       295
 3.0       183
 4.0       143
 5.0       104
 6.0       101
 7.0        58
 8.0        40
 10.0       32
 9.0        30
 12.0       25
 14.0       25
 15.0       20
 11.0       16
 13.0       14
 16.0       12
 18.0        9
 30.0        7
 17.0        6
 21.0        6
 22.0        5
 31.0        4
 51.0        4
 28.0        4
 32.0        3
 26.0        3
 170.0       3
 29.0        3
 23.0        3
 55.0        3
 54.0        2
 19.0        2
 53.0        2
 20.0        2
 42.0        2
 99.0        1
 80.0        1
 25.0        1
 168.0       1
 808.0       1
 35.0        1
 173.0       1
 71.0        1
 45.0        1
 190.0       1
 75.0        1
 227.0       1
 96.0        1
 107.0       1
 129.0       1
 128.0       1
 108.0       1
 104.0       1
 34.0        1
 266.0       1
Name: associatecurrbusinessestotal, dtype: int64
attribute_name : associatecurrsoscount
 0.0    1486
 1.0     918
-1.0     508
 2.0     319
 3.0     105
 4.0      29
 5.0      10
 6.0       4
 7.0       3
Name: associatecurrsoscount, dtype: int64
attribute_name : OpportunityID
0062M00000gYqZQQA0    1
0062M00000lrP8bQAE    1
0062M00000g8ojxQAA    1
0062M00000g8pG8QAI    1
0062M00000lrf8LQAQ    1
                     ..
0062M00000oPWWiQAO    1
0062M00000noKxKQAU    1
0062M00000noLSAQA2    1
0062M00000nomOVQAY    1
0062M00000l02kTQAQ    1
Name: OpportunityID, Length: 3382, dtype: int64
attribute_name : WriteOff_YN
0.0    2488
1.0     894
Name: WriteOff_YN, dtype: int64

In [ ]:
df.isna().sum()

associatecount                    0
associatebusinesscount            0
associatefelonycount              0
associatecountwithfelony          0
associatebankruptcount            0
associatecountwithbankruptcy      0
associatebankrupt12mcount         0
associateliencount                0
associatecountwithlien            0
associatejudgmentcount            0
associatecountwithjudgment        0
associatewatchlistcount           0
associatecitycount                0
associatecountycount              0
associatehighriskaddrcount        0
associatehighcrimeaddrcount       0
associatecurrcount                0
associatecurrcountwithfelony      0
associatecurrcountwithbkrpt       0
associatecurrcountwithlien        0
associatecurrcountwithjudgment    0
associatecurrcountwithprop        0
associatecurrbusinessestotal      0
associatecurrsoscount             0
OpportunityID                     0
WriteOff_YN                       0
dtype: int64

In [ ]:
df.columns

Index(['associatecount', 'associatebusinesscount', 'associatefelonycount',
       'associatecountwithfelony', 'associatebankruptcount',
       'associatecountwithbankruptcy', 'associatebankrupt12mcount',
       'associateliencount', 'associatecountwithlien',
       'associatejudgmentcount', 'associatecountwithjudgment',
       'associatewatchlistcount', 'associatecitycount', 'associatecountycount',
       'associatehighriskaddrcount', 'associatehighcrimeaddrcount',
       'associatecurrcount', 'associatecurrcountwithfelony',
       'associatecurrcountwithbkrpt', 'associatecurrcountwithlien',
       'associatecurrcountwithjudgment', 'associatecurrcountwithprop',
       'associatecurrbusinessestotal', 'associatecurrsoscount',
       'OpportunityID', 'WriteOff_YN'],
      dtype='object')

In [ ]:
def associate_attributes_FE(df):
  for i in df.columns:
    if i == 'OpportunityID' or i == 'WriteOff_YN':
      continue
    df[i+'_value'] = df[i].apply(lambda x:0 if x < 0 else x)
    df[i+'_flag'] = df[i].apply(lambda x: 1 if x < 0 else 0)
    df.drop(i,axis = 'columns',inplace = True)

In [ ]:
associate_attributes_FE(df)
df

,OpportunityID,WriteOff_YN,associatecount_value,associatecount_flag,associatebusinesscount_value,associatebusinesscount_flag,associatefelonycount_value,associatefelonycount_flag,associatecountwithfelony_value,associatecountwithfelony_flag,...,associatecurrcountwithlien_value,associatecurrcountwithlien_flag,associatecurrcountwithjudgment_value,associatecurrcountwithjudgment_flag,associatecurrcountwithprop_value,associatecurrcountwithprop_flag,associatecurrbusinessestotal_value,associatecurrbusinessestotal_flag,associatecurrsoscount_value,associatecurrsoscount_flag
0,0062M00000gYqZQQA0,0.0,2.0,0,2.0,0,0.0,0,0.0,0,...,2.0,0,1.0,0,2.0,0,2.0,0,0.0,0
1,0062M00000gYSpGQAW,0.0,3.0,0,12.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,2.0,0,10.0,0,1.0,0
2,0062M00000gYsQcQAK,0.0,1.0,0,5.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,1.0,0,5.0,0,1.0,0
3,0062M00000n0BEfQAM,0.0,1.0,0,6.0,0,0.0,0,0.0,0,...,1.0,0,1.0,0,1.0,0,6.0,0,1.0,0
4,0062M00000gYTaCQAW,1.0,2.0,0,13.0,0,0.0,0,0.0,0,...,1.0,0,1.0,0,2.0,0,13.0,0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3377,0062M00000lTxv8QAC,0.0,3.0,0,1.0,0,3.0,0,1.0,0,...,0.0,0,0.0,0,1.0,0,1.0,0,2.0,0
3378,0062M00000lTxyLQAS,0.0,1.0,0,1.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,1.0,0,1.0,0,0.0,0
3379,0062M00000jzsJkQAI,1.0,0.0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0
3380,0062M00000l01oMQAQ,1.0,0.0,1,0.0,1,0.0,1,0.0,1,...,0.0,1,0.0,1,0.0,1,0.0,1,0.0,1
3381,0062M00000l02kTQAQ,0.0,2.0,0,6.0,0,0.0,0,0.0,0,...,1.0,0,1.0,0,1.0,0,6.0,0,1.0,0

In [ ]:
round(df.corr()['WriteOff_YN'].sort_values(),3)

associatecurrcountwithprop_value       -0.067
associatecountycount_value             -0.058
associatecitycount_value               -0.056
associatecount_value                   -0.050
associatecountwithlien_value           -0.050
associateliencount_value               -0.046
associatehighcrimeaddrcount_value      -0.042
associatebusinesscount_value           -0.040
associatecurrcountwithlien_value       -0.035
associatecurrcount_value               -0.029
associatecurrbusinessestotal_value     -0.026
associatecountwithjudgment_value       -0.026
associatejudgmentcount_value           -0.020
associatecurrsoscount_value            -0.018
associatefelonycount_value             -0.011
associatecurrcountwithjudgment_value   -0.010
associatecountwithfelony_value         -0.007
associatehighriskaddrcount_value       -0.003
associatecurrcountwithfelony_value      0.003
associatecurrcountwithbkrpt_value       0.010
associatecountwithbankruptcy_value      0.010
associatebankruptcount_value            0.014
associatecurrcountwithfelony_flag       0.018
associatecurrcountwithbkrpt_flag        0.018
associatehighcrimeaddrcount_flag        0.018
associatecurrcountwithlien_flag         0.018
associatecurrcount_flag                 0.018
associatecurrbusinessestotal_flag       0.018
associatecurrcountwithjudgment_flag     0.018
associatecurrcountwithprop_flag         0.018
associatewatchlistcount_flag            0.018
associatecurrsoscount_flag              0.018
associatecountycount_flag               0.018
associatecitycount_flag                 0.018
associatecountwithjudgment_flag         0.018
associatejudgmentcount_flag             0.018
associatecountwithlien_flag             0.018
associateliencount_flag                 0.018
associatebankrupt12mcount_flag          0.018
associatecountwithbankruptcy_flag       0.018
associatebankruptcount_flag             0.018
associatecountwithfelony_flag           0.018
associatefelonycount_flag               0.018
associatebusinesscount_flag             0.018
associatecount_flag                     0.018
associatehighriskaddrcount_flag         0.018
associatebankrupt12mcount_value         0.020
WriteOff_YN                             1.000
associatewatchlistcount_value             NaN
Name: WriteOff_YN, dtype: float64

In [ ]:
round(data[associate_attributes].corr()['WriteOff_YN'].sort_values(),3)

associatecurrcountwithprop       -0.063
associatecountycount             -0.055
associatecitycount               -0.054
associatecount                   -0.049
associateliencount               -0.048
associatecountwithlien           -0.047
associatehighcrimeaddrcount      -0.042
associatebusinesscount           -0.040
associatecurrcountwithlien       -0.036
associatecurrcount               -0.031
associatecountwithjudgment       -0.029
associatecurrbusinessestotal     -0.026
associatejudgmentcount           -0.023
associatecurrsoscount            -0.021
associatecountwithfelony         -0.019
associatewatchlistcount          -0.018
associatehighriskaddrcount       -0.017
associatecurrcountwithjudgment   -0.017
associatefelonycount             -0.016
associatecurrcountwithfelony     -0.015
associatebankrupt12mcount        -0.014
associatecurrcountwithbkrpt      -0.008
associatecountwithbankruptcy     -0.007
associatebankruptcount           -0.004
WriteOff_YN                       1.000
Name: WriteOff_YN, dtype: float64

In [ ]:
df.to_excel("/content/drive/MyDrive/LCF_Internal/Renewable_Model/EDA Approach-1/XGBoost Implementation/v11/associate_attributes.xlsx")